import { StaticImages } from "./images";

export const flightListFilter = [
  { id: 1, text: "Sort" },
  { id: 2, text: "Fares" },
  { id: 3, text: "Airlines" },
  { id: 4, text: "Stops" },
  { id: 5, text: "Time" },
];

export const flightListData = [
  {
    id: 1,
    airline_logo: StaticImages.flightListLogo1,
    airline_name: "Delta Air Lines",
    start_time: "4:30pm",
    end_time: "6:13pm",
    price: "$322",
    boarding_point: "JFK",
    destination_point: "BOS",
    note: "",
    is_under_policy: true,
  },
  {
    id: 2,
    airline_logo: StaticImages.flightListLogo2,
    airline_name: "American Airlines",
    start_time: "8:30pm",
    end_time: "9:21pm",
    price: "$260",
    boarding_point: "JFK",
    destination_point: "BOS",
    note: "",
    is_under_policy: true,
  },
  {
    id: 3,
    airline_logo: StaticImages.flightListLogo1,
    airline_name: "Delta Air Lines",
    start_time: "12:30pm",
    end_time: "2:17pm",
    price: "$322",
    boarding_point: "JFK",
    destination_point: "BOS",
    note: "",
    is_under_policy: true,
  },
  {
    id: 4,
    airline_logo: StaticImages.flightListLogo1,
    airline_name: "Delta Air Lines",
    start_time: "6:30pm",
    end_time: "8:03pm",
    price: "$322",
    boarding_point: "JFK",
    destination_point: "BOS",
    note: "",
    is_under_policy: true,
  },
  {
    id: 5,
    airline_logo: StaticImages.flightListLogo2,
    airline_name: "American Airlines",
    start_time: "11:30pm",
    end_time: "12:20pm",
    price: "$2307",
    boarding_point: "JFK",
    destination_point: "BOS",
    note: "Operated by JetBlue Airways",
    is_under_policy: true,
  },
];
